// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.rust_lib;

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the detils of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.ptr.ByReference
import java.nio.ByteBuffer
import java.nio.ByteOrder

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    @JvmField var capacity: Int = 0
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : RustBuffer(), Structure.ByValue
    class ByReference : RustBuffer(), Structure.ByReference

    companion object {
        internal fun alloc(size: Int = 0) = rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_rust_lib_7fc3_rustbuffer_alloc(size, status).also {
                if(it.data == null) {
                   throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
               }
            }
        }

        internal fun free(buf: RustBuffer.ByValue) = rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_rust_lib_7fc3_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setInt(0, value.capacity)
        pointer.setInt(4, value.len)
        pointer.setPointer(8, value.data)
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): Int

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity.toLong()).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
@Structure.FieldOrder("code", "error_buf")
internal open class RustCallStatus : Structure() {
    @JvmField var code: Int = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    fun isSuccess(): Boolean {
        return code == 0
    }

    fun isError(): Boolean {
        return code == 1
    }

    fun isPanic(): Boolean {
        return code == 2
    }
}

class InternalException(message: String) : Exception(message)

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: Exception> rustCallWithError(errorHandler: CallStatusErrorHandler<E>, callback: (RustCallStatus) -> U): U {
    var status = RustCallStatus();
    val return_value = callback(status)
    if (status.isSuccess()) {
        return return_value
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
object NullCallStatusErrorHandler: CallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> rustCall(callback: (RustCallStatus) -> U): U {
    return rustCallWithError(NullCallStatusErrorHandler, callback);
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "uniffi_rust_lib"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface _UniFFILib : Library {
    companion object {
        internal val INSTANCE: _UniFFILib by lazy {
            loadIndirect<_UniFFILib>(componentName = "rust_lib")
            
        }
    }

    fun rust_lib_7fc3_simply_fetch_inbox_top(`domain`: RustBuffer.ByValue,`port`: Short,`username`: RustBuffer.ByValue,`password`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun rust_lib_7fc3_simply_send_plain_text_email(`smtpServer`: RustBuffer.ByValue,`smtpUsername`: RustBuffer.ByValue,`smtpPassword`: RustBuffer.ByValue,`headers`: RustBuffer.ByValue,`body`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun rust_lib_7fc3_simply_send_html_email(`smtpServer`: RustBuffer.ByValue,`smtpUsername`: RustBuffer.ByValue,`smtpPassword`: RustBuffer.ByValue,`headers`: RustBuffer.ByValue,`plainTextBody`: RustBuffer.ByValue,`htmlBody`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ffi_rust_lib_7fc3_rustbuffer_alloc(`size`: Int,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ffi_rust_lib_7fc3_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ffi_rust_lib_7fc3_rustbuffer_free(`buf`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): Unit

    fun ffi_rust_lib_7fc3_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Int,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    
}

// Public interface members begin here.


public object FfiConverterUByte: FfiConverter<UByte, Byte> {
    override fun lift(value: Byte): UByte {
        return value.toUByte()
    }

    override fun read(buf: ByteBuffer): UByte {
        return lift(buf.get())
    }

    override fun lower(value: UByte): Byte {
        return value.toByte()
    }

    override fun allocationSize(value: UByte) = 1

    override fun write(value: UByte, buf: ByteBuffer) {
        buf.put(value.toByte())
    }
}

public object FfiConverterUShort: FfiConverter<UShort, Short> {
    override fun lift(value: Short): UShort {
        return value.toUShort()
    }

    override fun read(buf: ByteBuffer): UShort {
        return lift(buf.getShort())
    }

    override fun lower(value: UShort): Short {
        return value.toShort()
    }

    override fun allocationSize(value: UShort) = 2

    override fun write(value: UShort, buf: ByteBuffer) {
        buf.putShort(value.toShort())
    }
}

public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len)
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteArr = value.toByteArray(Charsets.UTF_8)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteArr.size)
        rbuf.asByteBuffer()!!.put(byteArr)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    override fun allocationSize(value: String): Int {
        val sizeForLength = 4
        val sizeForString = value.length * 3
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteArr = value.toByteArray(Charsets.UTF_8)
        buf.putInt(byteArr.size)
        buf.put(byteArr)
    }
}




data class SmtpResponse (
    var `severity`: UByte, 
    var `category`: UByte, 
    var `detail`: UByte, 
    var `message`: String
) {
    
}

public object FfiConverterTypeSmtpResponse: FfiConverterRustBuffer<SmtpResponse> {
    override fun read(buf: ByteBuffer): SmtpResponse {
        return SmtpResponse(
            FfiConverterUByte.read(buf),
            FfiConverterUByte.read(buf),
            FfiConverterUByte.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: SmtpResponse) = (
            FfiConverterUByte.allocationSize(value.`severity`) +
            FfiConverterUByte.allocationSize(value.`category`) +
            FfiConverterUByte.allocationSize(value.`detail`) +
            FfiConverterString.allocationSize(value.`message`)
    )

    override fun write(value: SmtpResponse, buf: ByteBuffer) {
            FfiConverterUByte.write(value.`severity`, buf)
            FfiConverterUByte.write(value.`category`, buf)
            FfiConverterUByte.write(value.`detail`, buf)
            FfiConverterString.write(value.`message`, buf)
    }
}





sealed class ImapException(message: String): Exception(message) {
        // Each variant is a nested class
        // Flat enums carries a string error message, so no special implementation is necessary.
        class IoException(message: String) : ImapException(message)
        class TlsHandshakeException(message: String) : ImapException(message)
        class TlsException(message: String) : ImapException(message)
        class BadResponse(message: String) : ImapException(message)
        class NoResponse(message: String) : ImapException(message)
        class ConnectionLost(message: String) : ImapException(message)
        class ParseException(message: String) : ImapException(message)
        class ValidateException(message: String) : ImapException(message)
        class AppendException(message: String) : ImapException(message)
        class Nonexhaustive(message: String) : ImapException(message)
        

    companion object ErrorHandler : CallStatusErrorHandler<ImapException> {
        override fun lift(error_buf: RustBuffer.ByValue): ImapException = FfiConverterTypeImapError.lift(error_buf)
    }
}

public object FfiConverterTypeImapError : FfiConverterRustBuffer<ImapException> {
    override fun read(buf: ByteBuffer): ImapException {
        
            return when(buf.getInt()) {
            1 -> ImapException.IoException(FfiConverterString.read(buf))
            2 -> ImapException.TlsHandshakeException(FfiConverterString.read(buf))
            3 -> ImapException.TlsException(FfiConverterString.read(buf))
            4 -> ImapException.BadResponse(FfiConverterString.read(buf))
            5 -> ImapException.NoResponse(FfiConverterString.read(buf))
            6 -> ImapException.ConnectionLost(FfiConverterString.read(buf))
            7 -> ImapException.ParseException(FfiConverterString.read(buf))
            8 -> ImapException.ValidateException(FfiConverterString.read(buf))
            9 -> ImapException.AppendException(FfiConverterString.read(buf))
            10 -> ImapException.Nonexhaustive(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
        
    }

    override fun allocationSize(value: ImapException): Int {
        return 4
    }

    override fun write(value: ImapException, buf: ByteBuffer) {
        when(value) {
            is ImapException.IoException -> {
                buf.putInt(1)
                Unit
            }
            is ImapException.TlsHandshakeException -> {
                buf.putInt(2)
                Unit
            }
            is ImapException.TlsException -> {
                buf.putInt(3)
                Unit
            }
            is ImapException.BadResponse -> {
                buf.putInt(4)
                Unit
            }
            is ImapException.NoResponse -> {
                buf.putInt(5)
                Unit
            }
            is ImapException.ConnectionLost -> {
                buf.putInt(6)
                Unit
            }
            is ImapException.ParseException -> {
                buf.putInt(7)
                Unit
            }
            is ImapException.ValidateException -> {
                buf.putInt(8)
                Unit
            }
            is ImapException.AppendException -> {
                buf.putInt(9)
                Unit
            }
            is ImapException.Nonexhaustive -> {
                buf.putInt(10)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}





sealed class SmtpException(message: String): Exception(message) {
        // Each variant is a nested class
        // Flat enums carries a string error message, so no special implementation is necessary.
        class TransientSmtpException(message: String) : SmtpException(message)
        class PermanentSmtpException(message: String) : SmtpException(message)
        class ResponseParseException(message: String) : SmtpException(message)
        class InternalClientException(message: String) : SmtpException(message)
        class ConnectionException(message: String) : SmtpException(message)
        class NetworkException(message: String) : SmtpException(message)
        class TlsException(message: String) : SmtpException(message)
        class Timeout(message: String) : SmtpException(message)
        class OtherException(message: String) : SmtpException(message)
        

    companion object ErrorHandler : CallStatusErrorHandler<SmtpException> {
        override fun lift(error_buf: RustBuffer.ByValue): SmtpException = FfiConverterTypeSmtpError.lift(error_buf)
    }
}

public object FfiConverterTypeSmtpError : FfiConverterRustBuffer<SmtpException> {
    override fun read(buf: ByteBuffer): SmtpException {
        
            return when(buf.getInt()) {
            1 -> SmtpException.TransientSmtpException(FfiConverterString.read(buf))
            2 -> SmtpException.PermanentSmtpException(FfiConverterString.read(buf))
            3 -> SmtpException.ResponseParseException(FfiConverterString.read(buf))
            4 -> SmtpException.InternalClientException(FfiConverterString.read(buf))
            5 -> SmtpException.ConnectionException(FfiConverterString.read(buf))
            6 -> SmtpException.NetworkException(FfiConverterString.read(buf))
            7 -> SmtpException.TlsException(FfiConverterString.read(buf))
            8 -> SmtpException.Timeout(FfiConverterString.read(buf))
            9 -> SmtpException.OtherException(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
        
    }

    override fun allocationSize(value: SmtpException): Int {
        return 4
    }

    override fun write(value: SmtpException, buf: ByteBuffer) {
        when(value) {
            is SmtpException.TransientSmtpException -> {
                buf.putInt(1)
                Unit
            }
            is SmtpException.PermanentSmtpException -> {
                buf.putInt(2)
                Unit
            }
            is SmtpException.ResponseParseException -> {
                buf.putInt(3)
                Unit
            }
            is SmtpException.InternalClientException -> {
                buf.putInt(4)
                Unit
            }
            is SmtpException.ConnectionException -> {
                buf.putInt(5)
                Unit
            }
            is SmtpException.NetworkException -> {
                buf.putInt(6)
                Unit
            }
            is SmtpException.TlsException -> {
                buf.putInt(7)
                Unit
            }
            is SmtpException.Timeout -> {
                buf.putInt(8)
                Unit
            }
            is SmtpException.OtherException -> {
                buf.putInt(9)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




public object FfiConverterOptionalString: FfiConverterRustBuffer<String?> {
    override fun read(buf: ByteBuffer): String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: String?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}



public object FfiConverterMapStringString: FfiConverterRustBuffer<Map<String, String>> {
    override fun read(buf: ByteBuffer): Map<String, String> {
        // TODO: Once Kotlin's `buildMap` API is stabilized we should use it here.
        val items : MutableMap<String, String> = mutableMapOf()
        val len = buf.getInt()
        repeat(len) {
            val k = FfiConverterString.read(buf)
            val v = FfiConverterString.read(buf)
            items[k] = v
        }
        return items
    }

    override fun allocationSize(value: Map<String, String>): Int {
        val spaceForMapSize = 4
        val spaceForChildren = value.map { (k, v) ->
            FfiConverterString.allocationSize(k) +
            FfiConverterString.allocationSize(v)
        }.sum()
        return spaceForMapSize + spaceForChildren
    }

    override fun write(value: Map<String, String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        // The parens on `(k, v)` here ensure we're calling the right method,
        // which is important for compatibility with older android devices.
        // Ref https://blog.danlew.net/2017/03/16/kotlin-puzzler-whose-line-is-it-anyways/
        value.forEach { (k, v) ->
            FfiConverterString.write(k, buf)
            FfiConverterString.write(v, buf)
        }
    }
}
@Throws(ImapException::class)

fun `simplyFetchInboxTop`(`domain`: String, `port`: UShort, `username`: String, `password`: String): String? {
    return FfiConverterOptionalString.lift(
    rustCallWithError(ImapException) { _status ->
    _UniFFILib.INSTANCE.rust_lib_7fc3_simply_fetch_inbox_top(FfiConverterString.lower(`domain`), FfiConverterUShort.lower(`port`), FfiConverterString.lower(`username`), FfiConverterString.lower(`password`), _status)
})
}


@Throws(SmtpException::class)

fun `simplySendPlainTextEmail`(`smtpServer`: String, `smtpUsername`: String, `smtpPassword`: String, `headers`: Map<String, String>, `body`: String): SmtpResponse {
    return FfiConverterTypeSmtpResponse.lift(
    rustCallWithError(SmtpException) { _status ->
    _UniFFILib.INSTANCE.rust_lib_7fc3_simply_send_plain_text_email(FfiConverterString.lower(`smtpServer`), FfiConverterString.lower(`smtpUsername`), FfiConverterString.lower(`smtpPassword`), FfiConverterMapStringString.lower(`headers`), FfiConverterString.lower(`body`), _status)
})
}


@Throws(SmtpException::class)

fun `simplySendHtmlEmail`(`smtpServer`: String, `smtpUsername`: String, `smtpPassword`: String, `headers`: Map<String, String>, `plainTextBody`: String, `htmlBody`: String): SmtpResponse {
    return FfiConverterTypeSmtpResponse.lift(
    rustCallWithError(SmtpException) { _status ->
    _UniFFILib.INSTANCE.rust_lib_7fc3_simply_send_html_email(FfiConverterString.lower(`smtpServer`), FfiConverterString.lower(`smtpUsername`), FfiConverterString.lower(`smtpPassword`), FfiConverterMapStringString.lower(`headers`), FfiConverterString.lower(`plainTextBody`), FfiConverterString.lower(`htmlBody`), _status)
})
}




