// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(rust_libFFI)
import rust_libFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_rust_lib_7fc3_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_rust_lib_7fc3_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_PANIC: Int8 = 2

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: {
        $0.deallocate()
        return UniffiInternalError.unexpectedRustCallError
    })
}

private func rustCallWithError<T, F: FfiConverter>
    (_ errorFfiConverter: F.Type, _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T
    where F.SwiftType: Error, F.FfiType == RustBuffer
    {
    try makeRustCall(callback, errorHandler: { return try errorFfiConverter.lift($0) })
}

private func makeRustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T, errorHandler: (RustBuffer) throws -> Error) throws -> T {
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    switch callStatus.code {
        case CALL_SUCCESS:
            return returnedVal

        case CALL_ERROR:
            throw try errorHandler(callStatus.errorBuf)

        case CALL_PANIC:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

// Public interface members begin here.


fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


public struct SmtpResponse {
    public var `severity`: UInt8
    public var `category`: UInt8
    public var `detail`: UInt8
    public var `message`: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`severity`: UInt8, `category`: UInt8, `detail`: UInt8, `message`: String) {
        self.`severity` = `severity`
        self.`category` = `category`
        self.`detail` = `detail`
        self.`message` = `message`
    }
}


extension SmtpResponse: Equatable, Hashable {
    public static func ==(lhs: SmtpResponse, rhs: SmtpResponse) -> Bool {
        if lhs.`severity` != rhs.`severity` {
            return false
        }
        if lhs.`category` != rhs.`category` {
            return false
        }
        if lhs.`detail` != rhs.`detail` {
            return false
        }
        if lhs.`message` != rhs.`message` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`severity`)
        hasher.combine(`category`)
        hasher.combine(`detail`)
        hasher.combine(`message`)
    }
}


public struct FfiConverterTypeSmtpResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SmtpResponse {
        return try SmtpResponse(
            `severity`: FfiConverterUInt8.read(from: &buf), 
            `category`: FfiConverterUInt8.read(from: &buf), 
            `detail`: FfiConverterUInt8.read(from: &buf), 
            `message`: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SmtpResponse, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.`severity`, into: &buf)
        FfiConverterUInt8.write(value.`category`, into: &buf)
        FfiConverterUInt8.write(value.`detail`, into: &buf)
        FfiConverterString.write(value.`message`, into: &buf)
    }
}


public func FfiConverterTypeSmtpResponse_lift(_ buf: RustBuffer) throws -> SmtpResponse {
    return try FfiConverterTypeSmtpResponse.lift(buf)
}

public func FfiConverterTypeSmtpResponse_lower(_ value: SmtpResponse) -> RustBuffer {
    return FfiConverterTypeSmtpResponse.lower(value)
}


public enum ImapError {

    
    
    // Simple error enums only carry a message
    case IoError(message: String)
    
    // Simple error enums only carry a message
    case TlsHandshakeError(message: String)
    
    // Simple error enums only carry a message
    case TlsError(message: String)
    
    // Simple error enums only carry a message
    case BadResponse(message: String)
    
    // Simple error enums only carry a message
    case NoResponse(message: String)
    
    // Simple error enums only carry a message
    case ConnectionLost(message: String)
    
    // Simple error enums only carry a message
    case ParseError(message: String)
    
    // Simple error enums only carry a message
    case ValidateError(message: String)
    
    // Simple error enums only carry a message
    case AppendError(message: String)
    
    // Simple error enums only carry a message
    case Nonexhaustive(message: String)
    
}

public struct FfiConverterTypeImapError: FfiConverterRustBuffer {
    typealias SwiftType = ImapError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ImapError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .IoError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .TlsHandshakeError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .TlsError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .BadResponse(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .NoResponse(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .ConnectionLost(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .ParseError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .ValidateError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .AppendError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 10: return .Nonexhaustive(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ImapError, into buf: inout [UInt8]) {
        switch value {

        

        
        case let .IoError(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
        case let .TlsHandshakeError(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
        case let .TlsError(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
        case let .BadResponse(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
        case let .NoResponse(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
        case let .ConnectionLost(message):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(message, into: &buf)
        case let .ParseError(message):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(message, into: &buf)
        case let .ValidateError(message):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(message, into: &buf)
        case let .AppendError(message):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(message, into: &buf)
        case let .Nonexhaustive(message):
            writeInt(&buf, Int32(10))
            FfiConverterString.write(message, into: &buf)

        
        }
    }
}


extension ImapError: Equatable, Hashable {}

extension ImapError: Error { }


public enum SmtpError {

    
    
    // Simple error enums only carry a message
    case TransientSmtpError(message: String)
    
    // Simple error enums only carry a message
    case PermanentSmtpError(message: String)
    
    // Simple error enums only carry a message
    case ResponseParseError(message: String)
    
    // Simple error enums only carry a message
    case InternalClientError(message: String)
    
    // Simple error enums only carry a message
    case ConnectionError(message: String)
    
    // Simple error enums only carry a message
    case NetworkError(message: String)
    
    // Simple error enums only carry a message
    case TlsError(message: String)
    
    // Simple error enums only carry a message
    case Timeout(message: String)
    
    // Simple error enums only carry a message
    case OtherError(message: String)
    
}

public struct FfiConverterTypeSmtpError: FfiConverterRustBuffer {
    typealias SwiftType = SmtpError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SmtpError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .TransientSmtpError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .PermanentSmtpError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .ResponseParseError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .InternalClientError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .ConnectionError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .NetworkError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .TlsError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .Timeout(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .OtherError(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SmtpError, into buf: inout [UInt8]) {
        switch value {

        

        
        case let .TransientSmtpError(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
        case let .PermanentSmtpError(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
        case let .ResponseParseError(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
        case let .InternalClientError(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
        case let .ConnectionError(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
        case let .NetworkError(message):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(message, into: &buf)
        case let .TlsError(message):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(message, into: &buf)
        case let .Timeout(message):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(message, into: &buf)
        case let .OtherError(message):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(message, into: &buf)

        
        }
    }
}


extension SmtpError: Equatable, Hashable {}

extension SmtpError: Error { }

fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterDictionaryStringString: FfiConverterRustBuffer {
    public static func write(_ value: [String: String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterString.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: String] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: String]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

public func `simplyFetchInboxTop`(`domain`: String, `port`: UInt16, `username`: String, `password`: String) throws -> String? {
    return try FfiConverterOptionString.lift(
        try
    
    rustCallWithError(FfiConverterTypeImapError.self) {
    
    rust_lib_7fc3_simply_fetch_inbox_top(
        FfiConverterString.lower(`domain`), 
        FfiConverterUInt16.lower(`port`), 
        FfiConverterString.lower(`username`), 
        FfiConverterString.lower(`password`), $0)
}
    )
}



public func `simplySendPlainTextEmail`(`smtpServer`: String, `smtpUsername`: String, `smtpPassword`: String, `headers`: [String: String], `body`: String) throws -> SmtpResponse {
    return try FfiConverterTypeSmtpResponse.lift(
        try
    
    rustCallWithError(FfiConverterTypeSmtpError.self) {
    
    rust_lib_7fc3_simply_send_plain_text_email(
        FfiConverterString.lower(`smtpServer`), 
        FfiConverterString.lower(`smtpUsername`), 
        FfiConverterString.lower(`smtpPassword`), 
        FfiConverterDictionaryStringString.lower(`headers`), 
        FfiConverterString.lower(`body`), $0)
}
    )
}



public func `simplySendHtmlEmail`(`smtpServer`: String, `smtpUsername`: String, `smtpPassword`: String, `headers`: [String: String], `plainTextBody`: String, `htmlBody`: String) throws -> SmtpResponse {
    return try FfiConverterTypeSmtpResponse.lift(
        try
    
    rustCallWithError(FfiConverterTypeSmtpError.self) {
    
    rust_lib_7fc3_simply_send_html_email(
        FfiConverterString.lower(`smtpServer`), 
        FfiConverterString.lower(`smtpUsername`), 
        FfiConverterString.lower(`smtpPassword`), 
        FfiConverterDictionaryStringString.lower(`headers`), 
        FfiConverterString.lower(`plainTextBody`), 
        FfiConverterString.lower(`htmlBody`), $0)
}
    )
}



/**
 * Top level initializers and tear down methods.
 *
 * This is generated by uniffi.
 */
public enum RustLibLifecycle {
    /**
     * Initialize the FFI and Rust library. This should be only called once per application.
     */
    func initialize() {
    }
}